//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOS
    {
        public decimal CODIGOPDF { get; set; }
        public string NOMBREPDF { get; set; }
        public byte[] ARCHIVOPDF { get; set; }
    }
}
