//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS
    {
        public decimal ID_CITA { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public decimal ID_NOTARIA { get; set; }
        public decimal ID_ESTADO_CITA { get; set; }
    
        public virtual CITA_ESTADOS CITA_ESTADOS { get; set; }
        public virtual DOCUMENTOS_CITAS DOCUMENTOS_CITAS { get; set; }
        public virtual NOTARIAS NOTARIAS { get; set; }
    }
}
