//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA_ESTADOS
    {
        public CITA_ESTADOS()
        {
            this.CITAS = new HashSet<CITAS>();
        }
    
        public decimal ID_ESTADO_CITA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CITAS> CITAS { get; set; }
    }
}
