//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.EMPRESAS = new HashSet<EMPRESAS>();
            this.NOTARIAS = new HashSet<NOTARIAS>();
            this.TRIBUNAL = new HashSet<TRIBUNAL>();
        }
    
        public decimal ID_COMUNA { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_PROVINCIA { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual ICollection<EMPRESAS> EMPRESAS { get; set; }
        public virtual ICollection<NOTARIAS> NOTARIAS { get; set; }
        public virtual ICollection<TRIBUNAL> TRIBUNAL { get; set; }
    }
}
