//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS_CLIENTES
    {
        public decimal ID_CONTRATO { get; set; }
        public decimal ID_USUARIO { get; set; }
        public decimal ID_EMPRESA { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
