//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DILIGENCIAS
    {
        public decimal ID_DILIGENCIA { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> ID_CAUSA { get; set; }
    
        public virtual CAUSAS CAUSAS { get; set; }
    }
}
