//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_ESTADOS
    {
        public DOC_ESTADOS()
        {
            this.DOCUMENTOS_CITAS = new HashSet<DOCUMENTOS_CITAS>();
        }
    
        public decimal ID_ESTADO_DOC { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<DOCUMENTOS_CITAS> DOCUMENTOS_CITAS { get; set; }
    }
}
