//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS
    {
        public DOCUMENTOS()
        {
            this.DOCUMENTOS_CITAS = new HashSet<DOCUMENTOS_CITAS>();
        }
    
        public decimal ID_DOCUMENTO { get; set; }
        public string URL { get; set; }
        public System.DateTime CREADO { get; set; }
        public decimal ID_CONTRATO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual ICollection<DOCUMENTOS_CITAS> DOCUMENTOS_CITAS { get; set; }
    }
}
