//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS_CITAS
    {
        public decimal ID_CITA { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_ESTADO_DOC { get; set; }
        public System.DateTime CREADO { get; set; }
    
        public virtual CITAS CITAS { get; set; }
        public virtual DOC_ESTADOS DOC_ESTADOS { get; set; }
        public virtual DOCUMENTOS DOCUMENTOS { get; set; }
    }
}
