//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LexEntities : DbContext
    {
        public LexEntities()
            : base("name=LexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARCHIVOS> ARCHIVOS { get; set; }
        public DbSet<CAUSAS> CAUSAS { get; set; }
        public DbSet<CITA_ESTADOS> CITA_ESTADOS { get; set; }
        public DbSet<CITAS> CITAS { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CONTRATO_DETALLES> CONTRATO_DETALLES { get; set; }
        public DbSet<CONTRATO_ESTADOS> CONTRATO_ESTADOS { get; set; }
        public DbSet<CONTRATOS> CONTRATOS { get; set; }
        public DbSet<CONTRATOS_CLIENTES> CONTRATOS_CLIENTES { get; set; }
        public DbSet<DILIGENCIAS> DILIGENCIAS { get; set; }
        public DbSet<DOC_ESTADOS> DOC_ESTADOS { get; set; }
        public DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public DbSet<DOCUMENTOS_CITAS> DOCUMENTOS_CITAS { get; set; }
        public DbSet<EMPRESAS> EMPRESAS { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<NOTARIAS> NOTARIAS { get; set; }
        public DbSet<PAGOS> PAGOS { get; set; }
        public DbSet<PHOTOS> PHOTOS { get; set; }
        public DbSet<PLAN_PAGO> PLAN_PAGO { get; set; }
        public DbSet<PRESUPUESTO_DETALLES> PRESUPUESTO_DETALLES { get; set; }
        public DbSet<PRESUPUESTO_ESTADOS> PRESUPUESTO_ESTADOS { get; set; }
        public DbSet<PRESUPUESTOS> PRESUPUESTOS { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<SOLICITUD_ESTADOS> SOLICITUD_ESTADOS { get; set; }
        public DbSet<SOLICITUD_TIPOS> SOLICITUD_TIPOS { get; set; }
        public DbSet<SOLICITUDES> SOLICITUDES { get; set; }
        public DbSet<TRIBUNAL> TRIBUNAL { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
