//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public decimal ID_PAGO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public long MONTO { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public Nullable<decimal> ID_CONTRATO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
    }
}
