//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_PAGO
    {
        public PLAN_PAGO()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();
        }
    
        public decimal ID_PLAN_PAGO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }
    }
}
