//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTOS
    {
        public PRESUPUESTOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
        }
    
        public decimal ID_PRESUPUESTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public decimal ID_ESTADO_PRESUPUESTO { get; set; }
        public decimal ID_DETALLE_PRESUPUESTO { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public Nullable<decimal> ID_SOLICITUD { get; set; }
        public Nullable<decimal> ID_TECNICO { get; set; }
        public Nullable<decimal> ID_PLAN_PAGO { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual PLAN_PAGO PLAN_PAGO { get; set; }
        public virtual PRESUPUESTO_DETALLES PRESUPUESTO_DETALLES { get; set; }
        public virtual PRESUPUESTO_ESTADOS PRESUPUESTO_ESTADOS { get; set; }
        public virtual SOLICITUDES SOLICITUDES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
