//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tribunal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO_DETALLES
    {
        public PRESUPUESTO_DETALLES()
        {
            this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();
        }
    
        public decimal ID_DETALLE_PRESUPUESTO { get; set; }
        public string SERVICIO { get; set; }
        public long MONTO { get; set; }
    
        public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }
    }
}
